
disallowed-methods = [

    { path = "std::thread::sleep", reason = "Sleeping should not be used in tests as time is a controlled parameter. Additionally, sleeping can block async threads from proceeding." },
]


allow-expect-in-tests = true
allow-unwrap-in-tests = false
allow-panic-in-tests = false
allow-dbg-in-tests = true
allow-indexing-slicing-in-tests = true
