[book]
title = "Test Book"
authors = ["James Hodgkinson"]
language = "en"

[output.html]
additional-css = ["footer.css"]


[preprocessor.build-annotations]
command = "cargo run --bin mdbook-buildtime-annotations"
# the first n characters of the git commit hash to include in the annotation
commit_characters = 10
# the directory to look for a Cargo.toml in, relative to the book.
# defaults to "../" which is the parent directory of the book
# workspace_dir = "../"

# Defaults to true if unset, and determines whether to include the package name in the annotation
# package_name = true
# Defaults to true if unset, and determines whether to include the package version in the annotation
# package_version = true
# Defaults to true if unset, and determines whether to include the git commit in the annotation
# git_commit = true
